# Generated by Django 5.1.1 on 2026-02-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('common', '0002_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_users', to='common.address'),
        ),
    ]
