# Generated by Django 5.2.8 on 2026-01-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('postal_code', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('details', models.CharField(blank=True, max_length=45)),
            ],
        ),
    ]
