# Generated by Django 5.1.1 on 2026-01-25 14:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('STANDARD', 'Standard'), ('EXPRESS', 'Express')], default='STANDARD', max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='organizations.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'delivery_type'), name='uniq_comp_del_addr')],
            },
        ),
    ]
