# Generated by Django 5.1.1 on 2025-12-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("organizations", "0001_initial"),
        ("people", "0001_initial"),
        ("workforce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("IN_TRANSIT", "In transit"),
                            ("OUT_FOR_DELIVERY", "Out for delivery"),
                            ("DELIVERED", "Delivered"),
                            ("RETURNED", "Returned"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=45, unique=True)),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("EXPRESS", "Express")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_parcels",
                        to="common.address",
                    ),
                ),
                (
                    "pickup_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pickup_parcels",
                        to="common.address",
                    ),
                ),
                (
                    "receiver_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_parcels",
                        to="people.client",
                    ),
                ),
                (
                    "receiver_office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_parcels",
                        to="organizations.office",
                    ),
                ),
                (
                    "registered_by_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_parcels",
                        to="workforce.employee",
                    ),
                ),
                (
                    "sender_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_parcels",
                        to="people.client",
                    ),
                ),
                (
                    "sender_office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_parcels",
                        to="organizations.office",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcels",
                        to="parcels.parcelstatus",
                    ),
                ),
            ],
        ),
    ]
