# Generated by Django 5.1.1 on 2026-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_parcel_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='parcelstatus',
            name='name',
        ),
        migrations.AddField(
            model_name='parcelstatus',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IN_TRANSIT', 'In transit'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
    ]
