# Generated by Django 5.1.1 on 2026-02-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('parcels', '0003_remove_parcel_price_remove_parcelstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelstatus',
            options={'verbose_name_plural': 'Parcel statuses'},
        ),
        migrations.AlterModelOptions(
            name='parcelstatushistory',
            options={'verbose_name_plural': 'Parcel status histories'},
        ),
        migrations.RemoveField(
            model_name='parcelstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='parcel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='parcelstatus',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
