# Generated by Django 5.1.1 on 2026-01-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bulstat', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='common.address')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('working_hours', models.CharField(blank=True, max_length=60)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='common.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='organizations.company')),
            ],
        ),
    ]
