# Generated by Django 5.1.1 on 2025-12-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="employee_profile",
                        serialize=False,
                        to="accounts.appuser",
                    ),
                ),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("COURIER", "Courier"),
                            ("OFFICE", "Office staff"),
                            ("MANAGER", "Manager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organizations.office",
                    ),
                ),
            ],
        ),
    ]
