# Generated by Django 5.2.8 on 2026-01-18 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.office'),
        ),
    ]
